### ISSUE TITLE
chrome-tabs background color bleeding through individual tabs

### ISSUE THREAD

**Issue by Achilles1515** [adamschwartz/chrome-tabs#42] opened 2019-01-09 03:44 UTC
![untitled](https://user-images.githubusercontent.com/23387905/50872187-876e1b00-138c-11e9-92f5-79317fc855b7.png)

In the screenshot above (using Chrome as browser), I set...

```
.chrome-tabs {
    background: red;
}
```

...to emphasize the problem, and you may need to zoom in/resize the browser to reproduce the issue.

I was able to remove the bleeding vertical line by removing the inline `width="50%"` attribute in the "chrome-tab-geometry-right/left" `<svg>` HTML elements (or change it to something greater than 50%, but I think these width and height attributes can be removed entirely - their width and height percentages are already being set in the CSS?).

Not too sure about the bottom line.

**Comment by stekyne** [comment] 2019-01-10 17:14
This happened with the previous look as well. It would be great to get this resolved!

**Comment by adamschwartz** [comment] 2019-01-10 18:08
I’m not able to reproduce this in the latest stable version of Chrome running on macOS.

![image](https://user-images.githubusercontent.com/154613/50987861-c90bdc80-14d8-11e9-97ea-966f34de152f.png)

What browser (+ version) / OS are you running? And by any chance are you zooming the page?

**Comment by stekyne** [comment] 2019-01-10 20:17
![image](https://user-images.githubusercontent.com/2091399/50994573-8b2ca980-1514-11e9-8e4d-1d0938e49de3.png)

If I add enough tabs, the line appears. If I zoom in it also does appear but the pic above is 100% zoom. 
Using Chrome 71.0.3578.98 (latest), Windows 10.

**Comment by adamschwartz** [comment] 2019-01-10 21:09
@stekyne Thanks so much for that.

Would you also be willing to share your `devicePixelRatio`? You can get this by typing `devicePixelRatio` (or `window.devicePixelRatio`) into the Chrome DevTools console. For me the value is `2`, but I suspect for you it is `1`.

![image](https://user-images.githubusercontent.com/154613/50997161-d7b2bd80-14f1-11e9-9bc0-bb8e34c9728b.png)

This will further help me identify which cases I’ll need to fix. (Whether the issue is limited to Windows, systems with `devicePixelRatio`s other than `2`, etc.)

Thanks in advance for your help with this.

**Comment by stekyne** [comment] 2019-01-10 21:37
Yup, you are dead right. It was 1.

**Comment by adamschwartz** [comment] 2019-01-10 22:10
@stekyne Thanks again. I should be able to come up with a fix for this issue now.

**Comment by Achilles1515** [comment] 2019-01-10 22:30
1.25 devicePixelRatio for me. Windows 7, latest Chrome.

**Comment by adamschwartz** [comment] 2019-01-20 05:25
@Achilles1515 @stekyne I was unfortunately never able to reproduce the issue myself after testing on a few devices with different `devicePixelRatio`s. However, I hope that I was still able to fix the issue blind with https://github.com/adamschwartz/chrome-tabs/commit/d6cb603301f7d58609dd99fad2ca4d8efb57363c. Please let me know if you still see the issue with the latest version.

**Closed as completed by adamschwartz** 2019-01-20 05:25 UTC
Labels: bug

**Comment by stekyne** [comment] 2019-01-20 16:20
Looks good, I can't seem to reproduce the issue now.

**Comment by Achilles1515** [comment] 2019-01-21 15:18
Also looks fixed from my end. Thanks!
